#!/usr/bin/env python3
import json
import chiffrement
import rsa_key
import socket
import os

socket_attente = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
socket_attente.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
socket_attente.bind(('', 8080))
socket_attente.listen(socket.SOMAXCONN)


(socket_connectee, TSAP_client) = socket_attente.accept()
print(TSAP_client)
pid = os.fork()
liste=[]
e_s, d_s, n_s=rsa_key.gen_rsa_keys(5)
dico_key={"type":"key",
          "e":e_s,
          "n":n_s}
if pid:
    # je suis le parent
    while 1:
        ligne = socket_connectee.recv(1024)
        dico_message_recu = json.loads(ligne)
        if dico_message_recu["type"] == "message":
            message_crypted = dico_message_recu["data"]
            print(message_crypted)
            dechiffre=chiffrement.decrypt(d_s,message_crypted)
            print(dechiffre)
        elif dico_message_recu["type"]=="key":
            e_c=dico_message_recu["e"]
            n_c=dico_message_recu["n"]
            print(ligne)

        if not ligne:
            break
        #print(ligne)
else:
    # je suis l'enfant
    while 1:
        contenu = input(">")
        if contenu=="key":
            ligne=json.dumps(dico_key)
        else :            
            for i in contenu:
                liste.append(ord(i))
            message_crypted=chiffrement.encrypt(n_s,liste)
            print(message_crypted)
            dico_message={"type":"message",
                          "data":message_crypted}
            ligne=json.dumps(dico_message)
            #chaine = json.dumps(dico)
        if not contenu:
            break
        socket_connectee.sendall(ligne.encode('utf8'))

socket_connectee.close()
