#!/usr/bin/env python3
import json
import chiffrement
import rsa_key
import socket
import os, sys 

socket_connexion = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
socket_connexion.connect(('127.0.0.1', 8080))


#r,w=os.pipe()
e_c, d_c, n_c=rsa_key.gen_rsa_keys(5)
liste=[]
dico_key={"type": "key",
      "e":e_c,
      "n": n_c}
print(dico_key)
pid = os.fork()
if pid:
    # je suis le parent
    while 1:
       # ligne = input(">>")
        #if ligne
        #ligne=dico_key
        #if not ligne:
         #   break
        contenu = input(">>")

        if contenu=="key":
            ligne=json.dumps(dico_key)
        else :
            for i in contenu:
                liste.append(ord(i))
            message_crypted=chiffrement.encrypt(n_c,liste,d_c)
            print(message_crypted)
            dico_message={"type":"message",
                          "data":message_crypted}
            ligne=json.dumps(dico_message)

        if not contenu:
            break
        #dico={"type":ligne,
         #     "data":cle_pub,} #la virgule a la fin ne sert a rien

        #chaine = json.dumps(dico)
        #chaine = json.dumps(dico)
        #socket_connexion.sendall(ligne.encode('utf8'))
        socket_connexion.sendall(ligne.encode('utf-8'))
else:
    # je suis l'enfant
    while 1:
        ligne = socket_connexion.recv(1024)
        dico_message_recu = json.loads(ligne)
        if dico_message_recu["type"] == "message":
            message_crypted = dico_message_recu["data"]
            dechiffre=chiffrement.decrypt(d_c,message_crypted,n_c,e_c)

        elif dico_message_recu["type"]=="key":
            e_s=dico_message_recu["e"]
            n_s=dico_message_recu["n"]
            
            

        if not ligne:
            break
        print(ligne)
socket_connexion.close()
